// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4wmegSjd7mQOpNSyq-O1cf4UmTBBMOls',
    appId: '1:756328171123:web:e5faa0cdc3cbf323d10c06',
    messagingSenderId: '756328171123',
    projectId: 'khoyout-fe510',
    authDomain: 'khoyout-fe510.firebaseapp.com',
    storageBucket: 'khoyout-fe510.firebasestorage.app',
    measurementId: 'G-D73M2HYDYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeg4pZoV3fBjKOCt5wof49EExB0raOb5E',
    appId: '1:756328171123:android:ab69b0d6019cda57d10c06',
    messagingSenderId: '756328171123',
    projectId: 'khoyout-fe510',
    storageBucket: 'khoyout-fe510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5OaBdxn91EUsAfADEIj1ONlbvJmJn8Zs',
    appId: '1:756328171123:ios:db9f8d77123e5405d10c06',
    messagingSenderId: '756328171123',
    projectId: 'khoyout-fe510',
    storageBucket: 'khoyout-fe510.firebasestorage.app',
    iosBundleId: 'com.example.khouyot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5OaBdxn91EUsAfADEIj1ONlbvJmJn8Zs',
    appId: '1:756328171123:ios:db9f8d77123e5405d10c06',
    messagingSenderId: '756328171123',
    projectId: 'khoyout-fe510',
    storageBucket: 'khoyout-fe510.firebasestorage.app',
    iosBundleId: 'com.example.khouyot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4wmegSjd7mQOpNSyq-O1cf4UmTBBMOls',
    appId: '1:756328171123:web:7213d0d016d935fcd10c06',
    messagingSenderId: '756328171123',
    projectId: 'khoyout-fe510',
    authDomain: 'khoyout-fe510.firebaseapp.com',
    storageBucket: 'khoyout-fe510.firebasestorage.app',
    measurementId: 'G-GN4KG3YW1C',
  );
}
